# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dceab9a0-8dd1-4a85-9544-f3ba44ee0653";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/652a9f90-7145-475e-8d01-a5b0de971631";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/652a9f90-7145-475e-8d01-a5b0de971631";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/652a9f90-7145-475e-8d01-a5b0de971631";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AFDS-GADS";
	  fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/dceab9a0-8dd1-4a85-9544-f3ba44ee0653";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/dceab9a0-8dd1-4a85-9544-f3ba44ee0653";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
